apiVersion: apps/v1
kind: Deployment
metadata:
  name: eapp-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: eapp
  template:
    metadata:
      labels:
        app: eapp
    spec:
      containers:
        - name: eapp
          image: nandhini596/e_repo:v1   # your Docker Hub image
          ports:
            - containerPort: 5000
